application: rndphrase
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /
  static_files: index.html
  upload: index\.html

- url: /(.*)
  static_files: \1
  upload: .*\.(html|css|js|txt)


